---

sitename: Example gnrt.py website
baseurl: https://example.py
author: gnrt
language: en

defaults:
  template: default.j2
  category: page
  nav: includes/nav.html
  nav-order: 0
  published: 2020-01-01
  markdown-extras:
    - break-on-newline
    - fenced-code-blocks

lists:
  nav:
    template: nav.j2
    filter:
      key: category
      value: page
    sort: nav-order
  nav-all-articles:
    template: nav-article.j2
    filter:
      key: category
      value: article
    sort: published
    reverse: true
  nav-latest-articles:
    template: nav-article.j2
    filter:
      key: category
      value: article
    sort: published
    reverse: true
    limit: 2
  rss:
    filter:
      key: category
      value: article
    sort: published
    reverse: true
    template: rss.j2
    target: public/rss.xml
