---

name: Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip
        run: python -m pip install --upgrade pip

      - name: Install Task
        run: |
          sh -c "$(curl -ssL https://taskfile.dev/install.sh)" -- -d
          echo "./bin" >> $GITHUB_PATH

      - name: Build
        run: task build

      - name: QA
        run: task qa

      - name: Test
        run: task test
