---

name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get podmatrix
        run: |
          sudo wget https://raw.githubusercontent.com/jfhovinne/podmatrix/master/podmatrix -O /usr/local/bin/podmatrix
          sudo chmod +x /usr/local/bin/podmatrix

      - name: Test matrix
        run: |
          podmatrix exec ./test.sh --source . --target /tmp/src --image python \
          --tag 3.7 --tag 3.8 --tag 3.9 --tag 3.10 --tag 3.11
