---

name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test matrix
        run: |
          python3 -m venv /tmp/venv/
          source /tmp/venv/bin/activate
          ./vendor/bin/task test-matrix
